# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client:
  broker.gatewayAddress: 127.0.0.1:26500
  security.plaintext: true
  
identity.clientId: java
identity.clientSecret: e5xL9drBtKGEWF2bPiosjQGkVBTc4o0b
keycloakUrl: http://localhost:18080
tasklistUrl: http://localhost:8082/
operateUrl: http://localhost:8081/

# used to build links when sending mails
baseUrl: http://localhost:8080

# this is to allow react application launched separately to access the WS
websocket:
  allowedOrigin: "*"

# if set to true, process embedded forms will be pulled from tasklist. If false, forms will be pulled from the local process definitions available in resources.
embeddedForms.fromTasklist: false

spring:
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 30MB
  datasource:
    url: jdbc:h2:file:./h2/db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
