# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client:
  broker.gatewayAddress: 127.0.0.1:26500
  security.plaintext: true
  
identity.clientId: mydemoapplication
identity.clientSecret: rYb6aYOpo2qEipcoJgOxzL2RacbEbAga
keycloakUrl: http://localhost:18080
tasklistUrl: http://localhost:8082/
operateUrl: http://localhost:8081/

baseUrl: http://localhost:8080

websocket:
  allowedOrigin: "*"

embeddedForms.fromTasklist: false

spring:
  datasource:
    url: jdbc:h2:file:./h2/db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
